export const GET_FETCH_RECIPES_SUCCESS = 'GET_FETCH_RECIPES_SUCCESS';
export const GET_FETCH_CATEGORIES_SUCCESS = 'GET_FETCH_CATEGORIES_SUCCESS';
export const GET_FETCH_FILTERED_RECIPES_SUCCESS = 'GET_FETCH_FILTERED_RECIPES_SUCCESS';
export const GET_FETCH_SEARCH_FILTER_SUCCESS = 'GET_FETCH_SEARCH_FILTER_SUCCESS';
export const SHOW_ALL_CATEGORIES = 'SHOW_ALL_CATEGORIES';
